addons:
  sonarcloud:
    organization: "caay2000-github"
    token:
      secure: "${token}"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=caay2000_trains